qfall/math

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/get.rs, src/integer_mod_q/mat_zq/set.rs, src/macros/for_others.rs, src/traits.rs
Implementes getter and setter for MatZq.
=> getter and setter for MatZq

Cargo.toml, src/integer/mat_z.rs, src/integer/mat_z/from.rs, src/integer/mat_z/get.rs, src/integer/mat_z/ownership.rs, src/integer/mat_z/set.rs, src/integer/mat_z/to_string.rs, src/utils/parse.rs
Implements to_string for MatZ.
=> to_string for MatZ

src/error.rs, src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/from.rs
implements FromString for MatZq.
=> FromString for MatZq

src/rational/mat_q.rs, src/rational/mat_q/from.rs, src/rational/mat_q/get.rs, src/rational/mat_q/ownership.rs, src/rational/mat_q/set.rs, src/rational/mat_q/to_string.rs, src/rational/q/to_string.rs
Implements to_string for MatQ.
=> to_string for MatQ

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/to_string.rs, src/utils/parse.rs
Implements to_string for MatZq.
=> to_string for MatZq

src/integer/mat_z.rs, src/integer/mat_z/serialize.rs
This PR implements the Serialize and Deserialize trait for MatZ.
=> add serialize for MatZ

src/integer/mat_poly_over_z.rs, src/integer/mat_poly_over_z/serialize.rs, src/integer/poly_over_z/serialize.rs
This PR introduces implements the Serialize and Deserialize trait for MatPolyOverZ
=> add serialize to MatPolyOverZ

src/integer/mat_poly_over_z.rs, src/integer/mat_poly_over_z/transpose.rs
Implements transpose for MatPolyZ.
=> transpose for MatPolyZ

src/rational/mat_q.rs, src/rational/mat_q/transpose.rs
Implements transpose for MatQ.
=> transpose for MatQ

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/transpose.rs
Implements transpose for MatZq.
=> transpose for MatZq

src/integer/z.rs, src/integer/z/exp.rs, src/rational/poly_over_q.rs, src/rational/poly_over_q/exp.rs, src/rational/q.rs, src/rational/q/exp.rs
This PR introduces the ability to approximate the value of the exponential function for a given value. This works well for small values, but becomes less precise for large valeus. I will proceed by looking at different options, but this one allows to approximate the value of the exponential function easily using the Taylor series.
=> add exponential function using taylor polynomial

src/rational/mat_q/vector.rs, src/rational/mat_q/vector/dot_product.rs
Implements the dot_product for vectors in Q.
=> dot_product for vectors in Q

src/integer/mat_z/arithmetic.rs, src/integer/mat_z/arithmetic/mul_scalar.rs, src/macros/for_others.rs
Implements scalar multiplication for MatZ.
=> Scalar mul for MatZ

src/integer/mat_z.rs, src/integer/mat_z/concat.rs, src/traits.rs
This PR adds concatenation methods of MatZ.
=> Concat matrices

src/integer/mat_z/get.rs
=> get_vec for MatZ

src/integer/mat_poly_over_z.rs, src/integer/mat_poly_over_z/concat.rs
This PR implements ...
including tests for `MatPolyOverZ`.
=> MatPolyOverZ concatenate

src/integer/mat_z/concat.rs, src/rational/mat_q.rs, src/rational/mat_q/concat.rs
This PR implements ...
including tests for `MatQ`.
=> MatQ concatenate

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/concat.rs
This PR implements ...
including tests for `MatZq`.
=> MatZq concatenate

src/rational/mat_q/vector.rs, src/rational/mat_q/vector/norm.rs
This PR implements ..
including tests for `MatQ`.
=> MatQ Norms

src/integer/z.rs, src/integer/z/gcd.rs, src/macros/for_others.rs, src/traits.rs
=> Z `gcd` + `xgcd`

src/integer/mat_z/from.rs
This PR adds the ability to set a matrix to the identity matrix. The function set_one sets all entries on the diagonal to `1` and the remaining entries to `0`.
=> Set_one function for MatZ

src/error.rs, src/integer/z/arithmetic.rs, src/integer/z/arithmetic/pow.rs, src/integer/z/properties.rs
This PR implements
including tests for `Z`.
=> Z `pow` + `inv`

src/integer/z/from.rs, src/integer/z/to_string.rs
This PR adds the ability to provide a base for a to_string method in Z
=> To string method for Z with a providable base

src/rational/poly_over_q.rs, src/rational/poly_over_q/arithmetic.rs, src/rational/poly_over_q/arithmetic/add.rs, src/rational/poly_over_q/arithmetic/mul.rs, src/rational/poly_over_q/arithmetic/sub.rs, src/rational/poly_over_q/cmp.rs
the changes at cmp are part of an issue
=> arith polyoverQ

src/integer/z/properties.rs, src/integer/z/to_string.rs, src/rational/q.rs, src/rational/q/distance.rs, src/rational/q/from.rs, src/rational/q/properties.rs
=> Q `distance`

src/integer/mat_poly_over_z/get.rs
Implements get_vec for MatPolyZ.
=> get_vec for MatPolyZ

src/integer/mat_z/get.rs, src/rational/mat_q/get.rs
=> get_vec for MatQ

src/integer_mod_q/mat_zq/get.rs
=> get_vec for MatZq

src/integer/mat_z/from.rs, src/rational/mat_q/from.rs
=> MatQ identity

Cargo.toml, src/error.rs, src/utils.rs, src/utils/sample.rs, src/utils/sample/uniform.rs
=> Foundation for uniform random sampling

src/rational/mat_q.rs, src/rational/mat_q/gso.rs
=> gso for MatQ

src/error.rs, src/integer/mat_z.rs, src/integer/mat_z/determinant.rs, src/integer/mat_z/inverse.rs, src/integer/z/arithmetic/pow.rs, src/integer/z/properties.rs, src/integer_mod_q/z_q/properties.rs, src/rational/q/properties.rs
=> inverse for MatZ

src/integer/z.rs, src/integer/z/sample.rs
including tests for `Z`.
**Testing**
**Checklist:**
- Probably a little bit, but this way, the function is available for many types and is just a little bit less efficient.
=> Z `sample_uniform`

src/integer_mod_q/z_q.rs, src/integer_mod_q/z_q/sample.rs
including tests for `Zq`.
**Testing**
**Checklist:**
- Probably a little bit, but this way, the function is available for many types and is just a little bit less efficient.
=> Zq `sample_uniform`

src/integer/mat_z.rs, src/integer/mat_z/sample.rs
for `MatZ`.
**Testing**
**Checklist:**
- Probably a little bit, but this way, the function is available for many types and is just a little bit less efficient.
=> MatZ `sample_uniform`

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/sample.rs
for `MatZq`.
**Testing**
**Checklist:**
- Probably a little bit, but this way, the function is available for many types and is just a little bit less efficient.
=> MatZq `sample_uniform`

src/rational/q.rs, src/rational/q/rounding.rs
Rounding rationals may be necessary to reliable construct an integer from a `Q`. Rounding in general is a tool that is often used, hence adding this feature improves applicability for our library.
This PR adds the ability to round a rational `Q` to an integer value `Z`. The corresponding functionalitites are:
**Testing**
**Checklist:**
=> New Feature: Rounding from Q to Z

src/integer_mod_q/mat_zq/from.rs
This PR implements identity for MatZq.
**Testing**
**Checklist:**
=> identity for MatZq

src/integer/mat_z/arithmetic/mul_scalar.rs, src/rational/mat_q/arithmetic.rs, src/rational/mat_q/arithmetic/mul_scalar.rs
This PR implements mul_scalar for MatQ.
**Testing**
**Checklist:**
=> mul_scalar for MatQ

src/integer/z/logarithm.rs
for `Z`.
**Testing**
**Checklist:**
=> Z logarithm + improve availability

src/integer_mod_q/mat_zq/arithmetic.rs, src/integer_mod_q/mat_zq/arithmetic/mul_scalar.rs
This PR implements scalar multiplication for MatZq.
**Testing**
**Checklist:**
=> MatZq scalar

src/utils/sample/uniform.rs
=> Add security to uniform sampled byte function

src/error.rs, src/integer/mat_z.rs, src/integer/mat_z/trace.rs
This PR implements trace for MatZ.
**Testing**
**Checklist:**
=> trace for MatZ

src/integer_mod_q/mat_polynomial_ring_zq.rs
This PR initializes the struct MatPolyRingZq.
**Testing**
**Checklist:**
=> initialize MatPolyRingZq

src/rational/q/arithmetic/sub.rs
=> sub Q between types

src/rational/q/arithmetic/add.rs
=> add Q between types

src/integer_mod_q/z_q/arithmetic/add.rs
=> fixing memory leak

src/rational/q/arithmetic/div.rs
=> div Q between types

src/rational/q/arithmetic/mul.rs
=> mul Q between types

src/error.rs, src/rational/q/default.rs, src/utils/sample.rs, src/utils/sample/discrete_gauss.rs
=> Discrete Gaussian sampling

src/integer_mod_q/z_q/arithmetic/sub.rs
=> sub Zq between types

src/integer/z/arithmetic/div.rs
=> div Z between types

src/integer/z/arithmetic/mul.rs
=> mul Z between types

src/integer/mat_z/trace.rs
This PR fixes a doc comment in the trace function of MatZ.
**Testing**
**Checklist:**
=> MatZ trace doc comment

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/trace.rs
This PR implements trace for MatZq.
**Testing**
**Checklist:**
=> trace for MatZq

src/rational/mat_q.rs, src/rational/mat_q/trace.rs
This PR implements trace for MatQ.
**Testing**
**Checklist:**
=> trace for MatQ

src/integer/mat_poly_over_z.rs, src/integer/mat_poly_over_z/trace.rs
This PR implements trace for MatPolyZ.
**Testing**
**Checklist:**
=> trace for MatPolyZ

src/integer/poly_over_z.rs, src/integer/poly_over_z/sample.rs, src/integer/poly_over_z/sample/uniform.rs
for `PolyOverZ`.
**Testing**
**Checklist:**
=> PolyOverZ `sample_uniform`

src/integer_mod_q/poly_over_zq.rs, src/integer_mod_q/poly_over_zq/sample.rs, src/integer_mod_q/poly_over_zq/sample/uniform.rs
for `PolyOverZq`.
**Testing**
**Checklist:**
=> PolyOverZq `sample_uniform`

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/mat_polynomial_ring_zq/from.rs
This PR implements From PolyOverZ and Modulus_PolyOverZ for MatPolyRingZq.
**Testing**
**Checklist:**
=> From for MatPolyRingZq

src/rational/poly_over_q.rs, src/rational/poly_over_q/get.rs, src/rational/poly_over_q/norm.rs
for/ of `PolyOverQ`.
**Testing**
**Checklist:**
=> Poly over q norms

src/integer/poly_over_z.rs, src/integer/poly_over_z/get.rs, src/integer/poly_over_z/norm.rs
for/ of `PolyOverZ`.
**Testing**
**Checklist:**
=> norms poly over z

src/integer/mat_poly_over_z/set.rs, src/integer/mat_z/set.rs, src/integer_mod_q/mat_zq/set.rs, src/rational/mat_q/set.rs
for `MatZ`.
**Testing**
**Checklist:**
=> MatZ `swap` + `reverse`

src/integer_mod_q/mat_zq/set.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq `swap` and `reverse`

src/integer/mat_poly_over_z/set.rs
for `MatPolyOverZ`.
**Testing**
**Checklist:**
=> MatPolyOverZ `swap` and `reverse`

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/transpose.rs
This PR implements transpose for MatPolyRingZq.
**Testing**
**Checklist:**
=> transpose for MatPolyRingZq

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/vector.rs, src/integer_mod_q/mat_polynomial_ring_zq/vector/is_vector.rs
This PR implements is_vector for MatPolyRingZq.
**Testing**
**Checklist:**
=> is_vector for MatPolyRingZq

src/integer/mat_z/set.rs
for `MatZ`.
**Testing**
**Checklist:**
=> MatZ `set_row` and `set_column`

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
This PR implements Add for MatPolyRingZq.
**Testing**
**Checklist:**
=> Add for MatPolyRingZq

src/rational/mat_q/arithmetic/mul.rs
This PR implements multiplication for MatQ and MatZ.
**Testing**
**Checklist:**
=> Mul for MatQ and MatZ

src/integer_mod_q/mat_zq/arithmetic/mul.rs
This PR implements multiplication for MatZq and MatZ.
**Testing**
**Checklist:**
=> Mul for MatZq and MatZ

Cargo.toml, src/integer_mod_q/poly_over_zq.rs, src/integer_mod_q/poly_over_zq/get.rs, src/integer_mod_q/poly_over_zq/norm.rs
for/ of `PolyOverZq`.
**Testing**
**Checklist:**
=> norm poly over Zq

src/integer/mat_z/set.rs, src/integer_mod_q/mat_zq/set.rs, src/utils.rs, src/utils/collective_evaluation.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq `set_column` and `set_row`

src/rational/mat_q/set.rs
for `MatQ`.
**Testing**
**Checklist:**
=> MatQ `set_column` and `set_row`

src/integer/mat_poly_over_z/set.rs
for `MatPolyOverZ`.
**Testing**
**Checklist:**
=> MatPolyOverZ `set_column` and `set_row`

src/integer/mat_z/sort.rs, src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/sort.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq `sort`

src/integer/z/from.rs
=> Add Z from &Z

src/rational/q/from.rs
=> Add `From<&Q> for Q`

src/integer/z/arithmetic/root.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/mat_polynomial_ring_zq/from.rs, src/integer_mod_q/mat_polynomial_ring_zq/get.rs, src/integer_mod_q/mat_polynomial_ring_zq/reduce.rs, src/integer_mod_q/mat_polynomial_ring_zq/transpose.rs, src/integer_mod_q/mat_polynomial_ring_zq/vector/is_vector.rs, src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs, src/integer_mod_q/polynomial_ring_zq/from.rs, src/integer_mod_q/polynomial_ring_zq/reduce.rs
This PR implements collect_entries for MatPolyRingZq.
**Testing**
**Checklist:**
=> Collect_entries for MatPolyRingZq

src/integer/mat_poly_over_z/set.rs, src/integer/mat_z/set.rs, src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/mat_polynomial_ring_zq/from.rs, src/integer_mod_q/mat_polynomial_ring_zq/get.rs, src/integer_mod_q/mat_polynomial_ring_zq/reduce.rs, src/integer_mod_q/mat_polynomial_ring_zq/set.rs, src/integer_mod_q/mat_zq/set.rs, src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs, src/integer_mod_q/polynomial_ring_zq/from.rs, src/integer_mod_q/polynomial_ring_zq/reduce.rs, src/rational/mat_q/set.rs
This PR implements Set for MatPolyRingZq.
**Testing**
**Checklist:**
=> Set for MatPolyRingZq

src/error.rs, src/integer/z/arithmetic/root.rs, src/integer_mod_q/modulus_polynomial_ring_zq.rs, src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs, src/integer_mod_q/modulus_polynomial_ring_zq/from.rs, src/integer_mod_q/modulus_polynomial_ring_zq/ownership.rs, src/integer_mod_q/modulus_polynomial_ring_zq/serialize.rs, src/integer_mod_q/polynomial_ring_zq.rs
This PR fixes the issue that only primes could be entered into a modulus for polynomial rings.
**Testing**
**Checklist:**
=> fixed issue

src/rational/poly_over_q/from.rs
=> Add `PolyOverQ` from `Into<Q>`

src/integer/poly_over_z/from.rs
=> From basetype for PolyOverZ

src/rational/mat_q.rs, src/rational/mat_q/properties.rs, src/rational/poly_over_q.rs, src/rational/poly_over_q/properties.rs, src/rational/q/properties.rs
as a new https://github.com/qfall/math/pull/271 .
**Testing**
**Checklist:**
=> Q_Numtraits

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/solve.rs
This PR implements a solving algorithm for equations of the form `Ax = y`. As it uses Gaussian elimination, and elements might not be invertible, the algorithm does not perform perfect. Everything else should be covered in the related issue. Anyways, this PR implements a working implementation of solve, that can be used, until we implement the full version.
Works on #315 
**Testing**
**Checklist:**
=> First Version of Solve for Linear Equations mod q

src/integer/z/sample/uniform.rs
for `Z`.
**Testing**
**Checklist:**
=> Z `sample_prime_uniform`

src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq `sample_d`

src/integer/mat_z/sample/discrete_gauss.rs, src/utils/sample/discrete_gauss.rs
for/ of `MatZ`.
**Testing**
**Checklist:**
=> MatZ `sample_d_common`

src/integer/mat_poly_over_z/from.rs
Note : Requires rebase on dev once #318 is merged.
**Testing**
**Checklist:**
=> Add `From<MatZ> for MatPolyOverZ`

src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul.rs
This PR implements multiplication between two MatpolyRingZq objects.
**Testing**
**Checklist:**
=> Multiplication for MatPolyRingZq

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
This PR implements concatenate for MatPolyRingZq.
**Testing**
**Checklist:**
=> Concatenate for MatPolyRingZq

src/integer_mod_q/mat_polynomial_ring_zq/vector.rs, src/integer_mod_q/mat_polynomial_ring_zq/vector/dot_product.rs
This PR implements dot_product for MatPolyRingZq.
**Testing**
**Checklist:**
=> Dot_product for MatPolyRingZq

src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
Remove unwraps that are no longer required
=> Remove unwraps that are no longer required

benches/classic_crypto.rs, src/integer_mod_q/modulus/from.rs
This PR fixes an error in the benches file.
=> Error in benches

src/macros/arithmetics.rs, src/rational/q/arithmetic/div.rs
=> hotfix arithmetic between types

src/utils/sample/discrete_gauss.rs, src/utils/sample/uniform.rs
Remove a layer of indirection for randomness. This should make it thread safe.
=> Change the way ThreadRNG is used

src/integer/mat_z/arithmetic/div.rs
Suggestion on how to implement division for MatZ.
@Marcel583 if you want these changes, merge this PR into your MatZ_div branch.
(I will not improve this PR)
=> Partially implement divisions for MatZ with Integers.

src/error.rs, src/integer/mat_poly_over_z/arithmetic/add.rs, src/integer/mat_poly_over_z/arithmetic/sub.rs, src/integer/mat_z/arithmetic/add.rs, src/integer/mat_z/arithmetic/sub.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul.rs, src/integer_mod_q/mat_zq/arithmetic/add.rs, src/integer_mod_q/mat_zq/arithmetic/mul.rs, src/integer_mod_q/mat_zq/arithmetic/mul_scalar.rs, src/integer_mod_q/mat_zq/arithmetic/sub.rs, src/integer_mod_q/mat_zq/tensor.rs, src/integer_mod_q/poly_over_zq/arithmetic/add.rs, src/integer_mod_q/poly_over_zq/arithmetic/mul.rs, src/integer_mod_q/poly_over_zq/arithmetic/sub.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/mul.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/sub.rs, src/integer_mod_q/z_q/arithmetic/add.rs, src/integer_mod_q/z_q/arithmetic/mul.rs, src/integer_mod_q/z_q/arithmetic/sub.rs, src/rational/mat_q/arithmetic/add.rs, src/rational/mat_q/arithmetic/sub.rs
This PR correctss error messages`.
=> Correction of error messages

src/integer/z.rs, src/rational/q.rs
=> fix documentation, as Zq does not implement Into<Z>

src/integer/mat_poly_over_z/coefficient_embedding.rs, src/integer/poly_over_z/coefficient_embedding.rs, src/integer_mod_q/poly_over_zq.rs, src/integer_mod_q/poly_over_zq/coefficient_embedding.rs, src/rational/poly_over_q.rs, src/rational/poly_over_q/coefficient_embedding.rs
=> Coefficient Embedding for PolyOverZq and PolyOverQ

src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/inverse.rs
This PR implements inverse for MatZq with prime modulus.
**Testing**
**Checklist:**
=> Inverse for MatZq with prime modulus

src/integer/mat_z/arithmetic.rs, src/integer/mat_z/arithmetic/div.rs
This PR implements division for MatZ by Z.
**Testing**
**Checklist:**
=> Division for MatZ by Z

src/utils/sample/discrete_gauss.rs
This PR adds an explanation if the concentration bound test for sampleD fails
=> Add explanation if test fails

src/integer/mat_poly_over_z/vector.rs, src/integer/mat_poly_over_z/vector/dot_product.rs
This PR implements the dot_product for MatPolyZ.
**Testing**
**Checklist:**
=> dot_product for MatPolyZ

src/rational/poly_over_q.rs, src/rational/poly_over_q/dot_product.rs
This PR implements dot_product for PolyOverQ.
**Testing**
**Checklist:**
=> dot_product for PolyOverQ

src/integer/poly_over_z.rs, src/integer/poly_over_z/dot_product.rs
This PR implements dot_product for PolyOverZ.
**Testing**
**Checklist:**
=> dot_product for PolyOverZ

src/integer_mod_q/poly_over_zq.rs, src/integer_mod_q/poly_over_zq/dot_product.rs, src/integer_mod_q/poly_over_zq/get.rs
This PR implements dot_product for PolyOverZq.
**Testing**
**Checklist:**
=> dot_product for PolyOverZq

Cargo.toml, src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/polynomial_ring_zq.rs
This PR implements the Display trait for
**Checklist:**
=> Display trait to polynomial rings using derive_more

src/integer/mat_poly_over_z/sample/discrete_gauss.rs, src/integer_mod_q/mat_polynomial_ring_zq/sample/discrete_gauss.rs
The previous sampleD ring variant only worked for basis vectors of length 1, now higher dimensions are also possible.
**Testing**
**Checklist:**
=> Sample d ring fix

src/integer_mod_q/mat_polynomial_ring_zq/get.rs
=> get_mat for MatPolynomialRingZq

src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs, src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/sub.rs
This PR implements subtraction for MatPolyRingZq.
**Testing**
**Checklist:**
=> Sub for MatPolyRingZq

src/integer/poly_over_z/set.rs, src/integer_mod_q/poly_over_zq/set.rs, src/integer_mod_q/polynomial_ring_zq.rs, src/integer_mod_q/polynomial_ring_zq/set.rs, src/rational/poly_over_q/set.rs
This PR implements setter for PolyRingZq.
**Testing**
**Checklist:**
=> Setter for PolyRingZq

src/utils.rs, src/utils/factorization.rs, src/utils/factorization/default.rs, src/utils/factorization/from.rs, src/utils/factorization/ownership.rs, src/utils/factorization/refine.rs, src/utils/factorization/to_string.rs
This PR implements the Factorization object.
**Testing**
**Checklist:**
=> Factorization for Integers

src/integer/z/from.rs, src/integer/z/properties.rs
for `Z`.
**Testing**
**Checklist:**
=> Z `to_bits`, `from_bits`, `modulo`

src/integer/poly_over_z/sample.rs, src/integer/poly_over_z/sample/discrete_gauss.rs, src/integer/poly_over_z/sample/uniform.rs, src/integer_mod_q/modulus_polynomial_ring_zq/get.rs, src/integer_mod_q/poly_over_zq/sample.rs, src/integer_mod_q/poly_over_zq/sample/discrete_gauss.rs, src/integer_mod_q/poly_over_zq/sample/uniform.rs, src/integer_mod_q/polynomial_ring_zq.rs, src/integer_mod_q/polynomial_ring_zq/sample.rs, src/integer_mod_q/polynomial_ring_zq/sample/discrete_gauss.rs, src/integer_mod_q/polynomial_ring_zq/sample/uniform.rs
for `PolynomialRingZq`.
Furthermore, now
**Testing**
**Checklist:**
=> PolynomialRingZq `sample_uniform` & `sample_discrete_gauss`

src/integer_mod_q.rs, src/integer_mod_q/mat_zq.rs, src/integer_mod_q/mat_zq/set.rs, src/integer_mod_q/mat_zq/solve.rs, src/utils/collective_evaluation.rs
This PR extends the current version of solve for MatZq according to the linked issue.
**Testing**
**Checklist:**
=> Solve for MatZq

src/integer/z/properties.rs
for `Z`.
**Testing**
**Checklist:**
=> Z `is_perfect_power`

Cargo.toml, src/utils/sample.rs, src/utils/sample/binomial.rs, src/utils/sample/discrete_gauss.rs
=> Binomial Sampling

src/integer_mod_q/mat_zq/inverse.rs
This PR implements the Inverse function for MatZq.
**Testing**
**Checklist:**
=> Inverse for MatZq

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/properties.rs, src/integer_mod_q/mat_zq/properties.rs
This PR implements is_identity, is_zero and is_square for MatPolyRingZq.
**Testing**
**Checklist:**
=> MatPolyRingZq properties

src/integer_mod_q/z_q/sample.rs, src/integer_mod_q/z_q/sample/binomial.rs
for `Zq`.
**Testing**
**Checklist:**
=> Zq `sample_binomial`

src/integer/z/sample.rs, src/integer/z/sample/binomial.rs
for `Z`.
**Testing**
**Checklist:**
=> Z `sample_binomial`

src/integer.rs, src/integer_mod_q.rs, src/lib.rs, src/rational.rs
Previously opening the documentation did not provide an introduction to the general library.
This PR adds introductiory texts to the start of the documentation and each of the three modules `integer`, `integer_mod_q`, `rational`.
**Checklist:**
=> Module and Crate Description

src/integer/mat_z/sample.rs, src/integer/mat_z/sample/binomial.rs
for `MatZ`.
**Testing**
**Checklist:**
=> MatZ `sample_binomial`

src/integer_mod_q/mat_zq/sample.rs, src/integer_mod_q/mat_zq/sample/binomial.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq `sample_binomial`

src/integer/poly_over_z/sample.rs, src/integer/poly_over_z/sample/binomial.rs, src/integer/poly_over_z/sample/uniform.rs, src/integer_mod_q/polynomial_ring_zq/sample.rs, src/integer_mod_q/polynomial_ring_zq/sample/binomial.rs
for `PolyOverZ` and `PolynomialRingZq`.
**Testing**
**Checklist:**
=> PolyOverZ +  PolynomialRingZq `sample_binomial`

src/integer_mod_q/poly_over_zq/sample.rs, src/integer_mod_q/poly_over_zq/sample/binomial.rs
for `PolyOverZq`.
**Testing**
**Checklist:**
=> PolyOverZq `sample_binomial`

src/integer/mat_poly_over_z/sample.rs, src/integer/mat_poly_over_z/sample/binomial.rs, src/integer/mat_poly_over_z/sample/uniform.rs, src/integer_mod_q/mat_polynomial_ring_zq/sample.rs, src/integer_mod_q/mat_polynomial_ring_zq/sample/binomial.rs, src/integer_mod_q/mat_polynomial_ring_zq/sample/uniform.rs
for `MatPolyOverZ` and `MatPolynomialRingZq`.
**Testing**
**Checklist:**
=> binomial and uniform sampling for MatPolyOverZ and MatPolyRingZq

src/integer/mat_z/from.rs, src/integer_mod_q/mat_zq/get.rs
Also includes changes from #378, review and merge once #378 is merged.
**Testing**
- [ x I triggered all possible errors in my test in every possible way
**Checklist:**
=> Get closest to zero representative

benches/classic_crypto.rs, src/integer/mat_poly_over_z/get.rs, src/integer/z/arithmetic/div.rs, src/integer/z/cmp.rs, src/integer/z/from.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/mat_polynomial_ring_zq/reduce.rs, src/macros/for_others.rs, src/rational/q/arithmetic/logarithm.rs, src/rational/q/cmp.rs, src/utils/dimensions.rs, src/utils/sample/binomial.rs, src/utils/sample/uniform.rs
This PR refactors our macros and fixes some clippy warnings.
=> Refactor macros

README.md, src/integer/mat_z/inverse.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/poly_over_zq/norm.rs, src/integer_mod_q/z_q/distance.rs, src/integer_mod_q/z_q/from.rs, src/rational/poly_over_q/evaluate.rs, src/rational/poly_over_q/norm.rs, src/utils/sample/discrete_gauss.rs
=> Fixed TODOs

src/rational/mat_q.rs, src/rational/mat_q/rounding.rs
=> Round MatQ Entrywise

Cargo.toml, src/integer/z/sample/discrete_gauss.rs, src/rational/q.rs, src/rational/q/sample.rs, src/rational/q/sample/gauss.rs, src/rational/q/sample/gaussian.rs
=> Continuous Gaussian Sample for Q

src/rational/mat_q/rounding.rs, src/rational/q/rounding.rs
=> Randomized Rounding

.github/workflows/main.yml, .github/workflows/pull_request.yml, src/integer/mat_z/from.rs, src/integer_mod_q/mat_zq/get.rs, src/integer_mod_q/mat_zq/inverse.rs, src/integer_mod_q/mat_zq/sample/discrete_gauss.rs, src/integer_mod_q/mat_zq/solve.rs
This PR implements get_mat for MatZq.
**Testing**
**Checklist:**
=> Get_mat for MatZq

src/integer/mat_poly_over_z/to_string.rs, src/integer/mat_z/arithmetic/div.rs, src/integer/mat_z/to_string.rs, src/integer/poly_over_z/to_string.rs, src/integer/z/to_string.rs, src/integer_mod_q/mat_zq/get.rs, src/integer_mod_q/mat_zq/solve.rs, src/integer_mod_q/mat_zq/to_string.rs, src/integer_mod_q/modulus/to_string.rs, src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs, src/integer_mod_q/poly_over_zq/to_string.rs, src/integer_mod_q/z_q/to_string.rs, src/macros/for_others.rs, src/rational/mat_q/to_string.rs, src/rational/poly_over_q/to_string.rs, src/rational/q/to_string.rs
This PR implements the From trait for String with all our datatypes.
**Testing**
**Checklist:**
=> From for String

src/integer_mod_q/z_q/from.rs, src/integer_mod_q/z_q/to_string.rs
for `Zq`.
**Testing**
**Checklist:**
=> UTF8 En-/Decoding for Zq

src/integer/poly_over_z/to_string.rs, src/integer/z/to_string.rs, src/integer_mod_q/modulus/to_string.rs, src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs, src/integer_mod_q/poly_over_zq/to_string.rs, src/integer_mod_q/polynomial_ring_zq.rs, src/integer_mod_q/polynomial_ring_zq/from.rs, src/integer_mod_q/polynomial_ring_zq/to_string.rs, src/integer_mod_q/z_q/to_string.rs, src/rational/poly_over_q/to_string.rs, src/rational/q/to_string.rs
This PR implements to_string for PolynomialRingZq.
**Testing**
**Checklist:**
=> PolyRingZq to_string

Cargo.toml, src/integer_mod_q/modulus/cmp.rs
This PR implements Order for Modulus.
**Testing**
**Checklist:**
=> Modulus Order

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/to_string.rs, src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs
This PR implements to_string for MatPolyRingZq.
**Testing**
**Checklist:**
=> MatPolyRingZq to_string

src/integer/mat_poly_over_z/set.rs, src/integer/mat_z/set.rs, src/integer_mod_q/mat_polynomial_ring_zq/set.rs, src/integer_mod_q/mat_zq/set.rs, src/rational/mat_q/set.rs, src/utils/collective_evaluation.rs
This PR implements set_row and set_column for MatPolyRingZq.
**Testing**
**Checklist:**
=> MatPolyRingZq set_row and set_column

Cargo.toml, benches/benchmarks.rs, benches/cholesky_decomposition.rs, src/rational/mat_q/cholesky_decomp.rs, src/rational/q/sample/gauss.rs, src/utils/sample/binomial.rs, src/utils/sample/discrete_gauss.rs, src/utils/sample/uniform.rs
=> Optimize Cholesky Decomposition

src/rational/poly_over_q.rs, src/rational/poly_over_q/sample.rs, src/rational/poly_over_q/sample/gauss.rs
This PR implements sample_gauss for PolyOverQ.
**Testing**
**Checklist:**
=> PolyOverQ Sample_gauss

src/integer/poly_over_z/norm.rs, src/integer_mod_q/modulus_polynomial_ring_zq.rs, src/integer_mod_q/modulus_polynomial_ring_zq/norm.rs, src/integer_mod_q/poly_over_zq/norm.rs, src/rational/poly_over_q/norm.rs
This PR implements the Euclidean squared norm and the infinity norm for ModulusPolynomialRingZq.
**Testing**
**Checklist:**
=> ModulusPolynomialRingZq Norms

src/integer/mat_poly_over_z/vector.rs, src/integer/mat_poly_over_z/vector/norm.rs
This PR implements norms for MatPolyOverZ according to our implementations of norms for PolyOverZ and MatZ.
**Testing**
**Checklist:**
=> MatPolyOverZ Norms

src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/tensor.rs
This PR implements the tensor product for MatPolyRingZq.
**Testing**
**Checklist:**
=> MatPolyRingZq tensor

src/integer/z/from.rs
This PR just adjusts the current implementation to new expectations of clippy. Nothing fancy. Just so that new PRs don't fail because of it.
=> Make clippy happy

src/integer/mat_z/from.rs, src/integer_mod_q/mat_zq/from.rs, src/integer_mod_q/mat_zq/to_string.rs, src/utils/parse.rs
for `MatZq`.
**Testing**
**Checklist:**
=> MatZq UTF8

Cargo.toml, src/integer_mod_q/mat_polynomial_ring_zq/vector.rs, src/integer_mod_q/mat_polynomial_ring_zq/vector/norm.rs
This PR implements the Euclidean squared norm and the infinity norm for PolynomialRingZq.
**Testing**
**Checklist:**
=> MatPolyRingZq Norms

src/integer_mod_q/polynomial_ring_zq/from.rs
This PR implements From PolyOverZq for PolyRingZq.
**Testing**
**Checklist:**
=> From PolyOverZq for PolyRingZq

src/integer/mat_z/forms.rs, src/integer/mat_z/serialize.rs, src/rational/mat_q/cmp.rs, src/rational/mat_q/serialize.rs
This PR implements partialEq between MatZ and MatQ.
**Testing**
**Checklist:**
=> PartialEq between MatZ and MatQ

src/integer/mat_z/forms.rs, src/integer/poly_over_z/serialize.rs, src/integer_mod_q/mat_polynomial_ring_zq/default.rs, src/integer_mod_q/mat_polynomial_ring_zq/from.rs, src/integer_mod_q/mat_polynomial_ring_zq/get.rs, src/rational/poly_over_q/cmp.rs, src/rational/poly_over_q/serialize.rs
This PR implements PartialEq between PolyOverZ and PolyOverQ.
**Testing**
**Checklist:**
=> PartialEq between PolyOverZ and PolyOverQ

src/integer/mat_poly_over_z.rs, src/integer/mat_poly_over_z/sort.rs, src/integer/mat_z/forms.rs, src/integer/mat_z/sort.rs, src/integer_mod_q/mat_polynomial_ring_zq.rs, src/integer_mod_q/mat_polynomial_ring_zq/sort.rs, src/integer_mod_q/mat_zq/sort.rs, src/rational/mat_q/sort.rs
This PR implements sort_by_row/column for MatPolyOverZ and MatPolyRingZq.
**Testing**
**Checklist:**
=> Sort by row/column for MatPolyOverZ and MatPolyRingZq

src/integer/mat_z/arithmetic/mul_scalar.rs
This PR implements multiplication between MatZ and Q.
**Testing**
**Checklist:**
=> Scalar multiplication for MatZ

src/integer/mat_poly_over_z/arithmetic/sub.rs, src/integer/mat_z/arithmetic/sub.rs, src/integer_mod_q/mat_zq/arithmetic/sub.rs, src/rational/mat_q/arithmetic/sub.rs
This PR implements Sub between MatZ and MatQ.
**Testing**
**Checklist:**
=> Sub between MatZ and MatQ

src/integer/poly_over_z/arithmetic/sub.rs, src/integer_mod_q/poly_over_zq/arithmetic/sub.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/mul.rs, src/integer_mod_q/polynomial_ring_zq/arithmetic/sub.rs
This PR implements Mul, Add and Sub between PolyRingZq and PolyOverZq, PolyOverZ.
**Testing**
**Checklist:**
=> Operations between PolyRingZq and PolyOverZq, PolyOverZ

Cargo.toml
Update to newest dependency for criterion
=> update criterion dependency
