- src/integer/poly_over_z/evaluate.rs
- src/integer/poly_over_z/set.rs
- src/macros/for_others.rs
- src/rational/poly_over_q/evaluate.rs
This PR reworks the macro `implement_for_others` which is specifically designed to implement a certain trait for other inputs using implicit conversions. Additionally a macro is added which implements a trait with owned input using the trait with borrowed input.
Generally it reduces complexity in our macros and reduced loc.
> rework for others macro

- src/error.rs
- src/integer/poly_over_z/get.rs
- src/integer/z/default.rs
- src/integer/z/ownership.rs
- src/integer_mod_q/modulus/from.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/integer_mod_q/poly_over_zq/get.rs
- src/integer_mod_q/z_q/from.rs
This PR resolves a TODO in from_str for Modulus that remained since Z did not had to_string() nad from_str() at the time of implementation.
Additionally this PR introduces the constant ZERO for Z, which is especially useful for comparisons and increases readability.
This can be seen as separate from the default value, since we expect that the constant ZERO will not change, whereas the Default could potentially be changed.
> Resolve TODO in From_str Modulus

- src/integer_mod_q/poly_over_zq.rs
- src/integer_mod_q/poly_over_zq/evaluate.rs
This PR introduces the ability to evaluate a PolyOverZq for any of the following inputs
with the return value Zq.
> Evaluate for PolyOverZq

- src/rational/q/from.rs
Implement `Q::try_from` just for two borrowed integers.
The current implementation is not efficient and also not supporting
owned parameters.
Since the `Q` from integers functionality is needed, I decided to push this imperfect solution. 
A medium/larger rewrite might be required to accept all combinations of owned/borrowed, data types, and also avoid unnecessary clones.
The interface of the Trait should just accept more combinations after the rewrite. Therefore, the current `Q::try_from` trait implementation can be used without causing problems in the future.
> From int for `Q`

- src/integer/mat_z.rs
- src/integer/mat_z/vector.rs
- src/integer/mat_z/vector/is_vector.rs
including tests for `MatZ`.
Furthermore, I added a function `collect_entries` that efficiently collects all matrix entries without cloning any objects (incl. test).
> Vector Functions for MatZ

- src/integer_mod_q/mat_zq/serialize.rs
This PR adds a missing test for MatZq::serialize.
> add test for serialization of large negative MatZq

- src/integer_mod_q/mat_zq.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/vector.rs
- src/integer_mod_q/mat_zq/vector/is_vector.rs
> MatZq is_vector

- src/rational/mat_q.rs
- src/rational/mat_q/get.rs
- src/rational/mat_q/vector.rs
- src/rational/mat_q/vector/is_vector.rs
> MatQ is_vector

- src/error.rs
- src/integer/mat_z.rs
- src/integer/mat_z/get.rs
- src/integer/mat_z/vector.rs
- src/integer/mat_z/vector/dot_product.rs
- src/integer/mat_z/vector/is_vector.rs
- src/integer/mat_z/vector/norm.rs
incl. tests for `MatZ`. Furthermore, it adds a function that efficiently collects all `fmpz` values of a `MatZ` instance without cloning and adds doc tests to `MatZ`.
> MatZ Vector: Norms + Dot Product

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/evaluate.rs
This PR introduces the ability to evaluate a MatPolyOverZ entrywise with every reasonable type.
> add evaluation of MatPolyOverZ

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/get.rs
- src/integer/mat_poly_over_z/vector.rs
- src/integer/mat_poly_over_z/vector/is_vector.rs
This PR implements 
At first, I did not want to implement this. But as the `vector` part probably get's added to the `Matrix` trait, it should be implemented. Additionally, with a norm defined for polynomials (see [here](https://mathworld.wolfram.com/PolynomialNorm.html)), it seems realistic, that we will need this in the future.
> MatPolyOverZ is_vector

- src/integer/z/default.rs
- src/rational/q/default.rs
This PR implements
incl. tests for `Q` and 
incl. test for `Z`.
> Q Defaults

- src/integer/z.rs
- src/integer/z/from.rs
- src/integer/z/properties.rs
This PR implements useful leftovers from the `MatZq::norm` implementation. This includes
including tests for `Z`.
> Z Properties

- src/integer/mat_z.rs
- src/integer/mat_z/tensor.rs
- src/traits.rs
This PR adds the ability to compute the tensor product of two matrices: $A \otimes B$. For reference regarding correct implementation, one can look [here](https://en.wikipedia.org/wiki/Tensor_product).
> Tensor product for MatZ

- src/error.rs
- src/integer/z/properties.rs
- src/integer_mod_q/z_q/arithmetic.rs
- src/integer_mod_q/z_q/arithmetic/pow.rs
- src/macros/for_others.rs
- src/traits.rs
This PR implements missing pieces to be able to implement established public key encryption like RSA and El-Gamal with some additional help from other libraries using our data types.
Hence, it implements...
including tests.
> Toolbox for established PK encryption

- src/integer/z.rs
- src/integer/z/distance.rs
- src/integer/z/properties.rs
- src/macros/for_others.rs
- src/traits.rs
This PR refactors the implementation of `distance` for `Z`.
It implements a new trait `Distance` s.t. it can also be used for owned, borrowed, and u8, u16,... types.
This PR prepares an implementation of the `distance` trait for all numeric types.
> Z `distance`

- src/rational/poly_over_q/from.rs
#155
This PR fixes the reducing of coefficients of a PolyOverQ when instantiated from a string
> PolyOverQ: fix coefficients from_str not reduced

- src/integer.rs
- src/integer/mat_z.rs
- src/integer/mat_z/get.rs
- src/integer/mat_z/vector/dot_product.rs
- src/integer/mat_z/vector/norm.rs
- src/integer/z.rs
- src/integer/z/fmpz_helpers.rs
- src/integer_mod_q.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/vector.rs
- src/integer_mod_q/mat_zq/vector/norm.rs
- src/integer_mod_q/z_q.rs
- src/integer_mod_q/z_q/fmpz_mod_helpers.rs
- src/rational/mat_q/get.rs
several features needed to compute norms on `Zq` vectors like
and `norm_eucl_sqrd`, `norm_infty` for `MatZq` including tests.
> Norm MatZq

- src/error.rs
- src/integer/z/from.rs
This PR adds the ability to turn a `Z` value into an `i64`.
> add get_i64 for Z values

- src/integer/mat_z/tensor.rs
- src/integer_mod_q/mat_zq.rs
- src/integer_mod_q/mat_zq/tensor.rs
- src/traits.rs
This PR adds an implementation of the tensor product for MatZq.
> Tensor product for matzq

- src/rational/q/cmp.rs
Test cases mostly copied from `Z`.
But changed the values slightly in the first cases to ensure that numerator and denominator are compared.
> Add `PartialOrd` for `Q`

- src/integer/poly_over_z/arithmetic/add.rs
- src/integer/poly_over_z/arithmetic/mul.rs
- src/integer/poly_over_z/arithmetic/sub.rs
- src/integer/poly_over_z/from.rs
- src/integer/poly_over_z/set.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/rational/poly_over_q/from.rs
This closes #183.
The problem: fmpz_poly_set_str ignores both symbols after the number of coefficients, this is now fixed with a dedicated string. This issue does not occur for PolyOverQ. I added according tests in the from-methods
> fix parse error for PolyOverZ from_str

- src/integer/z/from.rs
- src/integer/z/properties.rs
> Z `from_bytes` and `bits`

- src/rational/q.rs
- src/rational/q/get.rs
This PR implements
**Testing**
**Checklist:**
> Add get_denominator and get_numerator for Q

- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_z/inverse.rs
Change comments to remove doc warnings
> Change comments to remove doc warnings

- src/integer_mod_q/poly_over_zq/from.rs
Added PolyZq from a tuple (&PolyZ, &Modulus). 
I did not implement it for owned parameters, because It will not lead to a (significant) performance improvement. This is because flint uses a different struct type for PolyZ and PolyZq => copying is necessary anyway.
**Testing**
**Checklist:**
> Add PolyZq from PolyZ and Modulus

- src/integer_mod_q/z_q/arithmetic/add.rs
- src/macros/arithmetics.rs
> Add_Zq_between_types

- src/rational/q/rounding.rs
Q numerators and denominators may grow arbitrary large. The simplify method returns the simplest rational in a defined range . This allows to save some memory for very large values.
**Testing**
**Checklist:**
> Simplification for Q

- src/integer_mod_q/z_q/arithmetic/mul.rs
> mul Zq between types

- src/error.rs
- src/integer/mat_poly_over_z/default.rs
- src/integer/mat_z/default.rs
- src/integer/z/distance.rs
- src/integer_mod_q/mat_zq.rs
- src/integer_mod_q/mat_zq/default.rs
- src/integer_mod_q/mat_zq/from.rs
- src/integer_mod_q/mat_zq/sample.rs
- src/integer_mod_q/modulus.rs
- src/integer_mod_q/modulus/cmp.rs
- src/integer_mod_q/modulus/from.rs
- src/integer_mod_q/poly_over_zq.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/integer_mod_q/polynomial_ring_zq.rs
- src/integer_mod_q/polynomial_ring_zq/from.rs
- src/integer_mod_q/z_q.rs
- src/integer_mod_q/z_q/from.rs
- src/rational/mat_q.rs
- src/rational/mat_q/default.rs
- src/rational/poly_over_q.rs
- src/rational/q.rs
- src/rational/q/from.rs
Also removed a confusing comment.
**Checklist:**
> Refactor sprint 6 part 2

- src/integer/z/from.rs
- rename `from_fmpz` to `from_fmpz_ref`
- Add `from_fmpz` that takes ownership. 
**Testing**
**Checklist:**
> change `from_fmpz` for `z`

- src/rational/poly_over_q/from.rs
The coeffcients of a PolyOverQ are in Q, hence it makes sense to be able to convert a PolyOverZ into a PolyOverQ in a natural and easy way. This PR makes this easy conversion possible.
**Testing**
**Checklist:**
> Conversion from PolyOverZ to PolyOverQ

- src/rational/mat_q/arithmetic/mul_scalar.rs
- src/rational/q/default.rs
- src/rational/q/distance.rs
- src/rational/q/from.rs
The current implementation of `Q::from_f64` was falty. This PR fixes it, such that all floats can be entered.
The new implementation looks at the value in memory, and takes the exact valeu represented. This means that values which can not be represented perfectly, will only use the bit represenatation from memory.
Subsequent changes had to be made to older tests, which either rounded or used lower precision.
This PR also updates the constant values for `e` and `pi` to 62 bit representation in denominator and numerator (more not possible due to Flints integer representation.
**Testing**
**Checklist:**
> Rework qfromf64

- src/integer/z/fmpz_helpers.rs
- src/integer_mod_q/z_q/fmpz_mod_helpers.rs
- src/rational/q.rs
- src/rational/q/cmp.rs
- src/rational/q/from.rs
- src/traits.rs
The `AsInteger` trait is intended to be used in other parts of the code as well.
It abstracts rust integers, `Z` and `Zq` into something that can be converted to `fmpz`.
Intended pattern if just a `&fmpz` is required (does not compile):
```rust
match a.get_fmpz_ref(){
None => let v = a.into_fmpz(); [...]; fmpz_clear(v),
v => [...]
}
```
Maybe a better syntax is possible with closures?
This PR ...
**Testing**
**Checklist:**
> From q refactor

- src/integer/z/arithmetic/root.rs
- src/rational/q/arithmetic.rs
- src/rational/q/arithmetic/root.rs
Add `sqrt` and `sqrt_precision` for `Q` 
Please also double check the calculation of the error bounds. It is in the module description.
**Testing**
**Checklist:**
> Sqrt for `Q`

- src/rational/mat_q.rs
- src/rational/mat_q/sort.rs
- src/rational/q/cmp.rs
for `MatZq` + `Ord` for `Q`.
**Testing**
**Checklist:**
> MatQ `sort` + Q `Ord`

- src/integer/mat_z/sample.rs
- src/integer/poly_over_z/sample/uniform.rs
- src/integer/z/fmpz_helpers.rs
- src/integer/z/from.rs
- src/integer/z/sample/uniform.rs
- src/integer_mod_q/mat_zq/sample.rs
- src/integer_mod_q/modulus.rs
- src/integer_mod_q/modulus/fmpz_helpers.rs
- src/integer_mod_q/poly_over_zq/sample/uniform.rs
- src/integer_mod_q/z_q/distance.rs
- src/integer_mod_q/z_q/get.rs
- src/integer_mod_q/z_q/sample/uniform.rs
- src/macros/for_others.rs
1. Rework the `From` trait for `Z` to use generics.
As a result, the documentation is shorter and references of rust integers are now also supported.
2. `Zq` can no longer be converted into `Z` with the from trait.
The reason for this is, that it is unclear which representation will be taken.
e.g. 3 mod 5 into 3, 8, 13, or ...?
For this reason, we prefer a dedicated function with an appropriate documentation (`get_value`).
As discussed during lunch.
=> Remove uses of `Z::from(Zq)` and `Z::from(&Zq)` (Sampling and distance)
3. Also fix doc comment for `Zq::distance`.
**Testing**
Some test cases have been joined (Modulus test into tests_from_int since it uses that Generic implementation)
Added test cases for the reference types, otherwise relied on existing test cases. …
> Refactor from for z

- src/integer/z/arithmetic/root.rs
Cargo clippy 0.1.70 falsely marks a clone as redundant. Added ignore for this warning.
> cargo clippy 0.1.70 falsely marks a clone as redundant.

- src/integer_mod_q/mat_zq/vector.rs
- src/integer_mod_q/mat_zq/vector/dot_product.rs
for `MatZq`.
It is way more convenient than `(vec_a.transpose() * vec_b).get_entry(0,0).unwrap()`.
**Testing**
**Checklist:**
> MatZq `dot_product`

- src/integer/mat_z/sample/discrete_gauss.rs
for `MatZ`.
The implementation of sample_discrete_gauss is needed for a comfortable sampling of error vectors where e <- \chi^m.
**Testing**
**Checklist:**
> MatZ `sample_discrete_gauss`

- src/integer/poly_over_z/from.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/integer_mod_q/polynomial_ring_zq.rs
- src/integer_mod_q/polynomial_ring_zq/from.rs
- src/integer_mod_q/polynomial_ring_zq/get.rs
Each PolynomialRingZq element consists of a modulus which is a PolyOverZq and a PolyOverZ. Users may want to access these polynomials. This PR makes it possible to get a copy of them in the repsective type. Additionally a PolyZq consists of a Modulus and a polynomial. This PR makes it possible to get a copy of the polynomial of the PolyZq.
**Testing**
Mostly did one test for large positive integers and a test for small positive integers in the doctest.
Tests for negative integers are not needed, as the values are always positive for these three conversions.
**Checklist:**
> Conversions between PolyZ, PolyZq and PolynomialRingZq

- src/integer_mod_q/mat_zq.rs
- src/integer_mod_q/mat_zq/properties.rs
- src/integer_mod_q/poly_over_zq/properties.rs
- src/integer_mod_q/z_q/properties.rs
as in https://github.com/qfall/math/pull/270
**Testing**
**Checklist:**
> Zq numtraits

- src/integer_mod_q/mat_zq/trace.rs
- src/integer_mod_q/mat_zq/vector/dot_product.rs
- src/integer_mod_q/z_q.rs
- src/integer_mod_q/z_q/from.rs
- src/integer_mod_q/z_q/properties.rs
- src/integer_mod_q/z_q/sample/discrete_gauss.rs
- src/integer_mod_q/z_q/sample/uniform.rs
Reasoning:
1. We can use the from trait now that does not return a Result.
2. If we would like to have a function that returns a Result, the naming would have to be changed anyway (maybe to something like `try_from_int_modulus`) and it should use generics.
**Testing**
**Checklist:**
> Rework from for zq

- Cargo.toml
- benches/benchmarks.rs
- benches/sampling.rs
- src/rational/poly_over_q/ownership.rs
- src/rational/q/arithmetic/exp.rs
- src/rational/q/from.rs
- src/utils/sample/discrete_gauss.rs
The new exp function makes the sample_d benchmark about **140** times faster.
**Testing**
**Checklist:**
> Exponential function optimization

- src/utils/sample/discrete_gauss.rs
SampleD does not need to sort the basis provided
> remove sort sampleD

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/coefficient_embedding.rs
- src/integer/poly_over_z.rs
- src/integer/poly_over_z/coefficient_embedding.rs
- src/traits.rs
In order to call functions like sampleD, we need to be able to interpret vectors as polynomials and vice versa.
This PR implements the corresponding methods.
**Testing**
**Checklist:**
> Coefficient embedding for PolyOverZ + MatPolyOverZ

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/sample.rs
- src/integer/mat_poly_over_z/sample/discrete_gauss.rs
- src/integer_mod_q/mat_polynomial_ring_zq.rs
- src/integer_mod_q/mat_polynomial_ring_zq/sample.rs
- src/integer_mod_q/mat_polynomial_ring_zq/sample/discrete_gauss.rs
- src/utils/sample/discrete_gauss.rs
In order to sample from a discrete Gaussian in the ring-setting, we require the sampleD to be implemented for the ring variants.
This is done via the coefficient embedding, i.e. every polynomial is interpreted as a vector and then one can simply use the previously implemented SampleD algorithm.
**Testing**
**Checklist:**
> SampleD Ring-Variant

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/tensor.rs
- src/integer/mat_z/tensor.rs
- src/integer_mod_q/mat_zq/tensor.rs
This PR implements
It resues an old implementation of the tensor product for MatZ. For MatZ we were able to use a dedicated method, for MatPolyOverZ, we are not able to -> hence reuse that implementation. The corresponding PR: <https://github.com/qfall/math/pull/160>
**Testing**
**Checklist:**
> Tensor product for MatPolyOverZ

- src/integer/mat_z/get.rs
Getting a certain window of a matrix appears to be very much needed to write nice tests and have a good code base.
This PR implements an efficient deep clone of the submatrix where we do not have to clone all entries more than once.
Additionally the window function is also directly applied for get_row and get_column to improve the code base with regards to less unsafe blocks and nicer to read code.
**Testing**
**Checklist:**
> Window Function for MatZ

- src/integer/mat_poly_over_z/get.rs
- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
- src/integer_mod_q/mat_zq/get.rs
- src/rational/mat_q/get.rs
This PR implements the window functionality for all other matrix types. These include
**Testing**
**Checklist:**
> Submatrix for other Matrix Types

- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
Direct accessing of entire rows and columns is a nice to have feature and already present for the other matrix types. This PR adds this functionality to MatPolynomialRingZq.
**Testing**
**Checklist:**
> Get_row and Get_column for MatPolynomialRingZq

- src/integer/mat_poly_over_z/get.rs
- src/integer/mat_poly_over_z/set.rs
- src/integer/mat_z/get.rs
- src/integer/mat_z/set.rs
- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/set.rs
- src/rational/mat_q/get.rs
- src/rational/mat_q/set.rs
- src/utils/index.rs
Add, document and test negative indexing for:
Did not add negative indexing for `set_column`, `set_row`, `swap_column`, `swap_rows`.
**Testing**
**Checklist:**
> Add negative indexing for Matrix entries.

- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/utils/sample/discrete_gauss.rs
Experiments in the crypto crate have shown that one of the main running time issues with current implementations using sample_d lies within the computation of the gso of a basis.
An intuitive approach is to precompute the gso and reuse it. In order to do this, we require that there is a sampleD algorithm that can take as input a precomputed gso of the base.
This PR makes it possible for
I intentionally left out MatPolyOverZ and MatPolynomialRingZq, as the way the gso would be provided needs some consideration, but I added a corresponding task in the Kanboard.
**Testing**
I decided to simply add a version using a precomputed gso to every existing test, as otherwise we would only have a lot of copied code.
**Checklist:**
> Sample_d with precomputed GSO

- src/integer/z/arithmetic/div.rs
just small addition quality of live improvement for another PR. 
- Into<Z> parameters for div_floor, div_ceil, and div_exact
**Testing**
**Checklist:**
> Different parameter types for `Z::div_(floor, ceil, exact)`

- src/integer_mod_q/mat_polynomial_ring_zq.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/modulus_polynomial_ring_zq.rs
- src/integer_mod_q/polynomial_ring_zq.rs
The PolynomialRing structs did not have any examples yet. This PR adds the corresponding examples to the structs and fixes an error in the implementation of set for matPolynomialRingZq.
**Testing**
**Checklist:**
> Add Struct descriptions to PolynomialRings + fix bug

- src/rational/mat_q.rs
- src/rational/mat_q/tensor.rs
This PR adds the Tensor-Product for MatQ. It was already supported for MatZ, MatZq and MatPolyOverZ, so adding this functionality to MatQ increases consistent usage for our types.
**Testing**
**Checklist:**
> Tensor product for MatQ

- src/integer_mod_q/mat_zq/to_string.rs
for/ of `MatZq`.
This is needed for the CCSfromIBE scheme in the crypto-crate s.t. it works properly for DualRegevIBE and PFDH together.
As the functionality is clear and it is already tested by the Display trait, I believe not more documentation/tests are necessary as already provided.
> Implement Into<String> for MatZq

- src/error.rs
- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_poly_over_z/vector/dot_product.rs
- src/integer/mat_z/from.rs
- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer/mat_z/sort.rs
- src/integer/mat_z/vector/dot_product.rs
- src/integer/poly_over_z/from.rs
- src/integer/z/arithmetic/logarithm.rs
- src/integer/z/arithmetic/root.rs
- src/integer/z/from.rs
- src/integer_mod_q/mat_polynomial_ring_zq/vector/dot_product.rs
- src/integer_mod_q/mat_zq/from.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sort.rs
- src/integer_mod_q/mat_zq/vector/dot_product.rs
- src/integer_mod_q/modulus/from.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/integer_mod_q/z_q/from.rs
- src/rational/mat_q/from.rs
- src/rational/mat_q/sort.rs
- src/rational/mat_q/vector/dot_product.rs
- src/rational/poly_over_q/from.rs
- src/rational/q/arithmetic/logarithm.rs
- src/rational/q/arithmetic/root.rs
- src/rational/q/from.rs
- src/utils/dimensions.rs
- src/utils/parse.rs
- src/utils/sample/discrete_gauss.rs
The `error` module was refactored in this PR.
The main steps taken are:
**Checklist:**
> Refactor Errors

- src/integer/mat_z/sample/discrete_gauss.rs
I decided to only implement the common version for now, as the more general version requires more extensive testing and as of right now, I only need the common version.
The PR is based on Algorithm 1 from <https://link.springer.com/chapter/10.1007/978-3-642-14623-7_5>.
**Testing**
**Checklist:**
> SampleD with a non-spherical Gaussian convolution matrix (with standard base and center 0)

- src/rational/q/default.rs
- src/rational/q/rounding.rs
The function `simplify` is capable of more than we thought. This PR makes sure that any developer is aware of the possibility to use it as a trade-off between precision and memory usage.
for `Q`.
**Testing**
**Checklist:**
> Make `Q::simplify` more viable

- src/integer/z/from.rs
- src/integer/z/to_string.rs
- src/utils/sample/binomial.rs
Introduces a way to turn text into `Z` integers that should be useful for a more vivid presentation of en-, decryption, etc.
It is a series of functions that I would like to implement to make our CTF challenges more appealing. These functions should also be implemented for `MatZ`, `Zq`, and `MatZq` for the time being.
for `Z`.
**Testing**
**Checklist:**
> Conversion between UTF8-encoded `Strings` and `Z`

- src/integer_mod_q/mat_polynomial_ring_zq/from.rs
We currently only have From for MatPolyRingZq with input MatPolyRingZq and  Into<ModulusPolynomialRingZq>. 
Since MatZ can be transformed into MatPolyRingZq, I changed our current implementation such that the input can be Into<MatPolyRingZq> and  Into<ModulusPolynomialRingZq>, without losing the efficiency of our current implementation.
**Testing**
**Checklist:**
> From for MatPolyRingZq with support for MatZ

- src/integer_mod_q/polynomial_ring_zq/get.rs
In case of PolyOverZq we have implemented GetCoefficient with a return value in Z and Zq. For PolyRingZq we currently only have GetCoefficient with a return value in Z.
**Testing**
**Checklist:**
> GetCoefficient of PolyRingZq as Zq

- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_z/from.rs
- src/integer_mod_q/mat_zq/from.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
- src/integer_mod_q/poly_over_zq/from.rs
- src/rational/mat_q/from.rs
This PR corrects the current implementation of ModulusPolyRingZq, since it did not check the polynomial modulus to be unequal to 0 and 1. 
It also implements...
for ModulusPolyRingZq.
**Testing**
**Checklist:**
> From for ModulusPolyRingZq

- src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
This PR implements the MismatchingModulus error for concatenation of MatPolyRingZq elements.
**Testing**
**Checklist:**
> MatPolyRingZq MismatchingModulus error for concatenation

- benches/classic_crypto.rs
- src/integer/mat_poly_over_z/arithmetic/mul.rs
- src/integer/mat_poly_over_z/arithmetic/sub.rs
- src/integer/poly_over_z/from.rs
- src/integer/poly_over_z/norm.rs
- src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/inverse.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
- src/integer_mod_q/poly_over_zq/get.rs
- src/integer_mod_q/polynomial_ring_zq/get.rs
- src/integer_mod_q/z_q/get.rs
- src/integer_mod_q/z_q/sample/discrete_gauss.rs
- src/integer_mod_q/z_q/to_string.rs
This PR implements get_representative for PolyOverZq and ModulusPolynomialRingZq. Furthermore, it deletes from<PolyOverZq> for PolyOverZ and renames the get_representative functions to a more meaningful name.
**Testing**
**Checklist:**
> PolyOverZq, ModulusPoly get_representative

- src/rational/mat_q/cholesky_decomp.rs
Problem: The current implementation of the cholesky decomposition is far to slow as
- We use a self-implementation
- We are working with [`Q`]s which have a high precision at the cost of runtime
Therefore I looked at ways to overcome these issues
- Using FLINTs function -> sadly not supported in FFI
- Use simplify to get to a certain precision -> too slow...
The latest of these options proved to be the best. As we can not access FLINTs function, I basically reformulated their implementation into Rust and used the same format.
**Testing**
-  Due to the precision - it does not work for large integers
**Checklist:**
> Cholesky Decomposition with less Precision

- src/integer/mat_z/arithmetic/mul.rs
- src/integer_mod_q/mat_zq/arithmetic/mul.rs
- src/macros/arithmetics.rs
- src/rational/mat_q/arithmetic/mul.rs
This PR fixes the multiplication between MatZ and MatZq, and between MatZ and MatQ. The multiplication A * B was treated the same way as B * A, this is now fixed by separate implementations and the macro that was used before is marked with a warning, that it should only be used for commutative operations.
**Testing**
**Checklist:**
> Matrix multiplication bug fix

- src/integer/mat_z/from.rs
- src/integer/mat_z/to_string.rs
- src/utils/parse.rs
for `MatZ`.
**Testing**
**Checklist:**
> UTF8-De-/Encoding for MatZ

- Cargo.toml
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
This PR implements all swap functions and reverse functions for MatPolyRingZq, based on their implementation for MatPolyOverZ.
**Testing**
**Checklist:**
> MatPolyRingZq swaps and reverses

- benches/benchmarks.rs
- benches/sample_z.rs
- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer/poly_over_z/sample/discrete_gauss.rs
- src/integer/z.rs
- src/integer/z/hash.rs
- src/integer/z/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/poly_over_zq/sample/discrete_gauss.rs
- src/integer_mod_q/z_q/sample/discrete_gauss.rs
- src/utils/sample/discrete_gauss.rs
This PR implements `DiscreteGaussianIntegerSampler` and sample_z to
Overall, the new implementation reduces discrete Gaussian sampling for a single sample by roughly 10 µs for the evaluated parameters (from 28 µs to 17 µs for a wide distribution and 18 µs to 9 µs for a narrow distribution).
If we sample multiple samples from the same distribution (usually done to sample the G-trapdoor R or preimages for G), then the speedup is just shy of 90% for 10,000 samples (280 ms -> 32 ms for a wide and 180 ms -> 19 ms for a narrow distribution).
**Testing**
**Checklist:**
> Revise `sample_z`

- src/integer_mod_q/modulus_polynomial_ring_zq.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/coefficient_embedding.rs
This PR implements coefficient embedding for ModulusPolynomialRingZq according to the implementation for PolyOverZq.
**Testing**
**Checklist:**
> ModPoly coefficient embedding

- src/utils.rs
- src/utils/sample.rs
- src/utils/sample/discrete_gauss.rs
This is required to enable quicker preimage-sampling for G-trapdoors in `qfall-crypto`.
> Make `DiscreteGaussianIntegerSampler` publicly available

- benches/benchmarks.rs
- benches/uniform.rs
- src/integer/mat_z/sample/uniform.rs
- src/integer/poly_over_z/sample/uniform.rs
- src/integer/z/from.rs
- src/integer/z/sample/uniform.rs
- src/integer_mod_q/mat_zq/sample/uniform.rs
- src/integer_mod_q/poly_over_zq/sample/uniform.rs
- src/integer_mod_q/z_q/sample/uniform.rs
- src/utils/sample.rs
- src/utils/sample/discrete_gauss.rs
- src/utils/sample/uniform.rs
It speeds uniform sampling up by roughly 65 to 80%. The problem with the old implementation was a slow conversion to Z, which is now much more efficient using u32 to u64 to Z conversion. This improvement outweights sampling more "unnecessary" bits. Furthermore, our benchmarks show that sampling u64's directly will decrease performance by roughly 20% (probably due to the  slow Z::mul in comparison to u64::mul.
Furthermore, uniform sampling is used in SampleZ, which speeds up its benchmarks by 20-50%.
Now, 75% of the time to sample a MatZq is determined by setting the entries in the matrix using MatZq::set_entry. Reducing the runtime of this by 2/3 can be done by using fmpz_mod_mat_set_entry after a quick test. This should be considered next
**Testing** …
> Optimize Uniform Sampling

- src/integer/z/from.rs
> Add u64::try_from<Z>

- src/integer/mat_poly_over_z/coefficient_embedding.rs
- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_poly_over_z/sample/binomial.rs
- src/integer/mat_poly_over_z/sample/uniform.rs
- src/integer/mat_poly_over_z/set.rs
- src/integer/mat_z/from.rs
- src/integer/mat_z/sample/binomial.rs
- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer/mat_z/sample/uniform.rs
- src/integer/mat_z/set.rs
- src/integer/poly_over_z/coefficient_embedding.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/mat_zq/from.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/sample/binomial.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sample/uniform.rs
- src/integer_mod_q/mat_zq/set.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/coefficient_embedding.rs
- src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
- src/macros/for_others.rs
- src/rational/mat_q/cholesky_decomp.rs
- src/rational/mat_q/rounding.rs
- src/rational/mat_q/sample/gauss.rs
- src/rational/mat_q/set.rs
- src/rational/poly_over_q/coefficient_embedding.rs
- src/traits.rs
This PR enables quicker filling of matrices, which is important for e.g. MatZ::sample_uniform, whose benchmarks execute faster by a factor of 40-60%. The same works for SampleZ benchmarks of MatZq::sample_discrete_gauss, which is quicker by ~10%.
**Testing**
No additional tests required as the `set_entry` functions now call the `set_entry_unchecked` function. Hence, any test for `set_entry` is automatically a test of `set_entry_unchecked`.
**Checklist:**
> Add `set_entry_unchecked`

- src/integer/mat_z.rs
- src/integer/mat_z/forms.rs
for `MatZ`.
**Testing**
**Checklist:**
> Normal Forms for `MatZ`

- benches/benchmarks.rs
- benches/matrix_arith.rs
- src/rational/mat_q/arithmetic/mul.rs
- src/rational/mat_q/cholesky_decomp.rs
- src/rational/mat_q/get.rs
- src/rational/q/from.rs
for `MatQ`.
For matrices with larger nominators & denominators, the MatQ::mul that doesn't allow for small precision loss is sometimes too inefficient. `mul_f64_unchecked` changes this by allowing for some loss of precision. This is a naive implementation of matrix multiplication with f64. It performs in the provided benchmark roughly 95% better than MatQ::mul.
**Testing**
**Checklist:**
> `MatQ` Multiplication with f64 precision

- src/integer/mat_z/get.rs
- src/integer/z/fmpz_helpers.rs
- src/integer/z/from.rs
- src/integer/z/ownership.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs
- src/rational/q/from.rs
- src/rational/q/get.rs
This PR replaces fmpz_set by fmpz_init_set where the value that is set is uninitialised (not set with a large number).
**Checklist:**
> Replace fmpz_set by fmpz_init_set

- benches/integer.rs
- src/integer/mat_poly_over_z/vector/norm.rs
- src/integer/poly_over_z/arithmetic/add.rs
- src/integer/poly_over_z/norm.rs
- src/integer/z/arithmetic/add.rs
- src/integer_mod_q/poly_over_zq/arithmetic/add.rs
- src/integer_mod_q/poly_over_zq/norm.rs
- src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs
- src/integer_mod_q/polynomial_ring_zq/norm.rs
- src/integer_mod_q/z_q/arithmetic/add.rs
- src/macros/arithmetics.rs
- src/rational/poly_over_q/arithmetic/add.rs
- src/rational/poly_over_q/norm.rs
- src/rational/q/arithmetic/add.rs
`AddAssign` is more than 70% quicker than `Add` for `Z`. It should yield at least the same improvement for any other type.
**Testing**
**Checklist:**
> Implement `AddAssign` for simple types

- src/integer/mat_poly_over_z/coefficient_embedding.rs
- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_poly_over_z/get.rs
- src/integer/mat_poly_over_z/properties.rs
- src/integer/mat_poly_over_z/tensor.rs
- src/integer/mat_poly_over_z/vector/norm.rs
- src/integer/mat_z/get.rs
- src/integer/mat_z/properties.rs
- src/integer/mat_z/to_string.rs
- src/integer/poly_over_z/coefficient_embedding.rs
- src/integer_mod_q/mat_polynomial_ring_zq/coefficient_embedding.rs
- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
- src/integer_mod_q/mat_polynomial_ring_zq/properties.rs
- src/integer_mod_q/mat_polynomial_ring_zq/tensor.rs
- src/integer_mod_q/mat_polynomial_ring_zq/vector/norm.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/properties.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/integer_mod_q/mat_zq/to_string.rs
- src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
- src/integer_mod_q/polynomial_ring_zq/coefficient_embedding.rs
- src/rational/mat_q/cholesky_decomp.rs
- src/rational/mat_q/get.rs
- src/rational/mat_q/properties.rs
- src/rational/mat_q/rounding.rs
- src/rational/poly_over_q/coefficient_embedding.rs
- src/traits.rs
**Testing**
No additional tests required as `get_entry` now uses `get_entry_unchecked`, which makes every test for `get_entry` a test for `get_entry_unchecked`.
**Checklist:**
> `get_entry_unchecked` for all Matrix Types

- src/integer/mat_poly_over_z/coefficient_embedding.rs
- src/integer/mat_poly_over_z/from.rs
- src/integer/mat_poly_over_z/sample/binomial.rs
- src/integer/mat_poly_over_z/sample/uniform.rs
- src/integer/mat_poly_over_z/set.rs
- src/integer/mat_z/from.rs
- src/integer/mat_z/sample/binomial.rs
- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer/mat_z/sample/uniform.rs
- src/integer/mat_z/set.rs
- src/integer/poly_over_z/coefficient_embedding.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/mat_zq/from.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/sample/binomial.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sample/uniform.rs
- src/integer_mod_q/mat_zq/set.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/coefficient_embedding.rs
- src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
- src/integer_mod_q/polynomial_ring_zq/coefficient_embedding.rs
- src/macros/for_others.rs
- src/rational/mat_q/cholesky_decomp.rs
- src/rational/mat_q/rounding.rs
- src/rational/mat_q/sample/gauss.rs
- src/rational/mat_q/set.rs
- src/rational/poly_over_q/coefficient_embedding.rs
- src/traits.rs
This PR implements makes `set_entry_unchecked` unsafe for all matrix types.
This is due to different error types / undefined behaviour if the entry isn't part of the matrix.
> Make `set_entry_unchecked` unsafe

- src/rational/mat_q/to_string.rs
- src/rational/poly_over_q/to_string.rs
- src/rational/q/to_string.rs
> Decimal representation for `Q`,`MatQ` and `PolyOverQ`

- src/integer/mat_z/arithmetic/add.rs
- src/integer/mat_z/arithmetic/sub.rs
- src/integer_mod_q/mat_zq/arithmetic/add.rs
- src/integer_mod_q/mat_zq/arithmetic/sub.rs
between MatZ and MatZq.
**Testing**
**Checklist:**
> `Add` & `Sub` between `MatZ` and `MatZq`

- src/integer/mat_poly_over_z/arithmetic/add.rs
- src/integer/mat_z/arithmetic/add.rs
- src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
- src/integer_mod_q/mat_zq/arithmetic/add.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/rational/mat_q/arithmetic/add.rs
This PR implements `AddAssign` for ...
**Testing**
**Checklist:**
> `AddAssign` for Matrices

- src/integer/mat_z/forms.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/serialize.rs
- src/integer_mod_q/poly_over_zq/serialize.rs
This PR implements PartialEq between PolyOverZq and ModPoly.
**Testing**
**Checklist:**
> PartialEq between PolyOverZq and ModPoly

- src/integer/mat_poly_over_z/get.rs
- src/integer/mat_poly_over_z/sort.rs
- src/integer/mat_z/get.rs
- src/integer/mat_z/sort.rs
- src/integer_mod_q/mat_polynomial_ring_zq/get.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/mat_polynomial_ring_zq/sort.rs
- src/integer_mod_q/mat_zq/get.rs
- src/integer_mod_q/mat_zq/norm.rs
- src/integer_mod_q/mat_zq/solve.rs
- src/integer_mod_q/mat_zq/sort.rs
- src/rational/mat_q/cholesky_decomp.rs
- src/rational/mat_q/get.rs
- src/rational/mat_q/norm.rs
- src/rational/mat_q/sort.rs
- src/traits.rs
- src/utils/sample/discrete_gauss.rs
This PR reworks how we have implemented getters for rows and columns for matrices.
The new implementation is easier to maintain and has less code redundancy.
Additionally I...
**Testing**
I did not add additional dedicated tests for the unchecked matrices, as I think they are sufficiently tested through the checked methods that call them
**Checklist:**
> Rework Getters for Matrices by accessing via Submatrices

- src/integer/mat_poly_over_z/arithmetic/modulo.rs
- src/integer/mat_z/arithmetic/modulo.rs
- src/integer/poly_over_z/arithmetic/modulo.rs
- src/integer/z/arithmetic/modulo.rs
- src/integer_mod_q/mat_polynomial_ring_zq/set.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/unsafe_functions.rs
This PR extends the current remainder trait to also capture the modulus.
Furthermore, it removes an error in the ModulusPolynomialRingZq, where it was possible to instantiate it with a polynomial of degree 0.
**Testing**
**Checklist:**
> Extend remainder trait

- src/rational/mat_q/to_string.rs
- src/rational/poly_over_q/to_string.rs
- src/rational/q/to_string.rs
This PR...
Downside of this: Rounding is less clear. It requires knowledge of how a number is represented in floating point arithmetic to understand the output (mostly relevant for the case if `nr_decimal_digits = 0`).
> Revise decimal representation of `Q`, `MatQ` and `PolyOverQ`

- src/integer/mat_poly_over_z/unsafe_functions.rs
- src/integer/mat_z/unsafe_functions.rs
- src/integer/poly_over_z/unsafe_functions.rs
- src/integer/z/unsafe_functions.rs
- src/integer_mod_q/mat_polynomial_ring_zq/unsafe_functions.rs
- src/integer_mod_q/mat_zq/unsafe_functions.rs
- src/integer_mod_q/modulus/unsafe_functions.rs
- src/integer_mod_q/modulus_polynomial_ring_zq/unsafe_functions.rs
- src/integer_mod_q/poly_over_zq/unsafe_functions.rs
- src/integer_mod_q/polynomial_ring_zq/unsafe_functions.rs
- src/integer_mod_q/z_q/unsafe_functions.rs
- src/macros/unsafe_passthrough.rs
- src/rational/mat_q/unsafe_functions.rs
- src/rational/poly_over_q/unsafe_functions.rs
- src/rational/q/unsafe_functions.rs
> Add `unsafe` Setters

- src/integer/mat_z/arithmetic/sub.rs
- src/rational/mat_q/arithmetic/add.rs
- src/rational/mat_q/arithmetic/sub.rs
No additional tests required as the function uses the `add_safe` / `sub_safe` which is already tested.
> `Add` & `Sub` between `MatQ` & `MatZ`

- src/integer_mod_q/modulus_polynomial_ring_zq/unsafe_functions.rs
Removes the use of ModulusPolynomialRingZq::from(Zq), which was disabled as the behaviour of a modulus "1  3 mod 7" is not properly defined.
> Fix problem on dev

- src/integer/mat_poly_over_z.rs
- src/integer/mat_poly_over_z/norm.rs
- src/integer/mat_poly_over_z/vector/norm.rs
- src/integer/mat_z/norm.rs
- src/integer_mod_q/mat_polynomial_ring_zq.rs
- src/integer_mod_q/mat_polynomial_ring_zq/norm.rs
- src/integer_mod_q/mat_polynomial_ring_zq/vector/norm.rs
- src/rational/mat_q/norm.rs
for MatPolyOverZ and MatPolynomialRingZq.
**Testing**
No additional tests required as they are based on well-tested functions - the vector norms and just iterate over each column.
**Checklist:**
> Matrix Norms for `MatPolyOverZ` and `MatPolynomialRingZq`

- benches/classic_crypto.rs
- src/integer/mat_poly_over_z/sample/binomial.rs
- src/integer/mat_poly_over_z/sample/discrete_gauss.rs
- src/integer/mat_poly_over_z/sample/uniform.rs
- src/integer/mat_z/sample/binomial.rs
- src/integer/mat_z/sample/discrete_gauss.rs
- src/integer/mat_z/sample/uniform.rs
- src/integer/poly_over_z/sample/binomial.rs
- src/integer/poly_over_z/sample/discrete_gauss.rs
- src/integer/poly_over_z/sample/uniform.rs
- src/integer/z/sample/binomial.rs
- src/integer/z/sample/discrete_gauss.rs
- src/integer/z/sample/uniform.rs
- src/integer_mod_q/mat_polynomial_ring_zq/sample/binomial.rs
- src/integer_mod_q/mat_polynomial_ring_zq/sample/discrete_gauss.rs
- src/integer_mod_q/mat_zq/sample/binomial.rs
- src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
- src/integer_mod_q/poly_over_zq/sample/binomial.rs
- src/integer_mod_q/poly_over_zq/sample/discrete_gauss.rs
- src/integer_mod_q/polynomial_ring_zq/sample/binomial.rs
- src/integer_mod_q/z_q/sample/binomial.rs
- src/integer_mod_q/z_q/sample/discrete_gauss.rs
- src/integer_mod_q/z_q/sample/uniform.rs
- src/utils/sample/binomial.rs
- src/utils/sample/discrete_gauss.rs
- src/utils/sample/uniform.rs
This PR removes the following "overprotective" measures from samplers...
Furthermore, this PR implements the more efficient discrete Gaussian sampler (for sampling with static Gaussian parameters across all entries) for matrices over polynomials, i.e.
**Testing**
**Checklist:**
> Remove overprotective measures from samplers
